### ISSUE TITLE
Add "Release Date" attribute to content 

### ISSUE THREAD

**Issue by kauffj** [lbryio/types#10]
_From @tzarebczan on September 22, 2017 21:23_

 

## The Issue
The need to have a release date tag arose during LBRY YouTube sync discussions with @reillysmith .  Oftentimes users will want the need to display videos on a channel according to their release date. Right now, all videos are sorted by publish date, which equates to the block they were published or updated on - this may not always be the desired sort order.  

The requirement would be to add a Release Date attribute to uploaded content. If not populated, it should default to publish date (original block date if update later) - open to discussion. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots

_Copied from original issue: lbryio/lbry#921_

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
consider after signatures

**Comment by shyba** [comment]
isnt this a duplicate of #13 ?

**Comment by tzarebczan** [comment]
Yes, closing.
