### ISSUE TITLE
Add tags to schema

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/types#16]
We should allow publishers to set tags for their uploaded content. Would need to discuss implementation details, for example, how many tags do we allow and how is it stored in the metadata. If we want community overlays to work properly, each tag may need to exist on its own, as opposed to a list of tags.

**Comment by kauffj** [comment]
For a first version of tags my proposal is that we allow a completely free-form system (perhaps autocompleting from chainquery app-side) limiting to `n` tags (~5).

**Comment by tzarebczan** [comment]
I also like the idea of a type attribute for the tag, or some way to specify which tags are responsible for things like categories/topics/genres (i.e. first tag is always the category). I think this will aide on the discovery side.
