### ISSUE TITLE
Add support/stake attributes to metadata

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/types#20]
Some ideas:
1) Note/Comment/Description (like a permanent comment?)
2) Signature (sign stakes with channels?)

See original discussion in https://github.com/lbryio/lbry/issues/919 

Trying to determine if there's a way to tell tips vs supports at the surface, without a type. Seems like comparing to the claim address is the only way, so we should not need this in the metadata. This breaks currently when the claim is updated, so we need to make sure claim updates keep the same address, but we may still want to pursue the type as a configured attribute.

**Comment by tzarebczan** [comment]
Sounds like this one requires blockchain changes. Will get that issue filed if it's not already.

**Comment by alyssaoc** [comment]
closing in favor of #919
