### ISSUE TITLE
Determine proper pattern for type-specific metadata

### ISSUE THREAD

**Issue by kauffj** [lbryio/types#23]
Recent changes are add new fields like `duration` which do not apply to all media types (a spreadsheet does not have a duration).

We could easily end up with thousands of metadata properties when we consider type-specific attributes.

What's the correct pattern for this? If it's to define type-specific metadata structures, then it may not be proper to add `duration` at the top-level for all items.

**Comment by alyssaoc** [comment]
@lyoshenka what is next for this?

**Comment by lyoshenka** [comment]
i need to do this eventually

**Comment by lyoshenka** [comment]
the solution we're going with is to put type-specific fields into their own types

https://github.com/lbryio/types/blob/master/v2/proto/claim.proto#L27
