### ISSUE TITLE
Add 3 letter language codes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/types#44]
https://en.wikipedia.org/wiki/ISO_639-3

Otherwise we can't differentiate between traditional and simplified chinese

**Comment by eukreign** [comment]
This is already supported by existing implementation of RFC 5646. Traditional is `zh-Hant` and simplified is `zh-Hans`.

https://github.com/lbryio/types/blob/f0b4476ef386b096e99e64c6cf8a7ed20ca92d5f/v2/proto/claim.proto#L299

https://github.com/lbryio/types/blob/f0b4476ef386b096e99e64c6cf8a7ed20ca92d5f/v2/proto/claim.proto#L363

https://github.com/lbryio/types/blob/f0b4476ef386b096e99e64c6cf8a7ed20ca92d5f/v2/proto/claim.proto#L362
