### ISSUE TITLE
Rename content_type to media_type

### ISSUE THREAD

**Issue by kauffj** [lbryio/types#6]
`media_type` is the specific term for the property being provided.

`content_type` is a legacy term that is used because HTTP uses it.

https://stackoverflow.com/questions/9258108/whats-the-difference-between-mediatype-contenttype-and-mimetype

**Comment by lyoshenka** [comment]
!snooze

**Comment by lyoshenka** [comment]
started on this in #17

**Comment by lyoshenka** [comment]
continuing in https://github.com/lbryio/types/pull/17
