### ISSUE TITLE
Add channel related metadata columns

### ISSUE THREAD

**Issue by kauffj** [lbryio/types#8]
At a minimum:

1) Name
2) Thumbnail
3) Cover
4) Description

Other considerations:
1) Primary Language
2) Featured video
3) Other channels 
4) Playlists?

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
We need channel attributes but I am disinclined to double-down on the poor choice that was a single boolean property called `is_nsfw`.

**Comment by alyssaoc** [comment]
we should consider this after the signature changes

**Comment by lyoshenka** [comment]
what does Name mean here? don't channels already have a name? is this like the difference between `username` and `display name`?

**Comment by lyoshenka** [comment]
moving discussion to https://github.com/lbryio/types/pull/17
