### ISSUE TITLE
Add file attributes to metadata

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/types#9]
Schema related changes for: https://github.com/lbryio/lbry/issues/918 

Add the following metadata fields:

- `file` - a dictionary with info about the file. this will grow eventually. for now it should have:
  - `name` - the filename. 255 chars max.
  - `size` - the size of the original file
  - `duration` - an integer that represents how many seconds long the file is. only applies to files that have a duration, like audio or video file.

In the future, we may want to add `hash` (a hash of the original file) to that dictionary as well, but we will leave it out for now.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
@KamilPiekutowski Please let us know if there's any particular questions you have about this ticket and the other one for release date.

**Comment by alyssaoc** [comment]
after signatures

**Comment by jackrobison** [comment]
Another to add is `contentHash` - this is the hash of the unencrypted file that the stream assembles into.

**Comment by tzarebczan** [comment]
@lyoshenka, @jackrobison and I ran into the real reason we need the contentHash...so one could update a claim without having the file download (metadata only) and reconstruct the file list entry with the contentHash for consistency.

**Comment by lyoshenka** [comment]
> reconstruct the file list entry

not sure i understand this. what do you mean?

**Comment by tzarebczan** [comment]
Jack originally wanted to re-create the file_list entry for the edited file in stopped/incomplete mode, but then we decided not to do that. @jackrobison do we still want this?

**Comment by tzarebczan** [comment]
@jackrobison should we be adding file hash in this go around? What does it help with again?

**Comment by tzarebczan** [comment]
Nevermind, hash is in the PR.
